import {
  calculateOverallScore,
  type AttributeScores,
  type FeedActivity,
  type Profile,
  type ProfileWithStats,
  type ReviewComment,
  type ReviewPhoto,
  type SecretSpotRequest,
  type SpaceWithAttributes,
  type UserRanking,
} from '@/types/space';

const now = new Date().toISOString();

const MONTH_NAMES = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];
const daysAgo = (days: number) => new Date(Date.now() - days * 24 * 60 * 60 * 1000).toISOString();
// Demo event reviews mention dates relative to today so the calendar always has something to show.
const dayFromNow = (offset: number) => {
  const date = new Date();
  date.setDate(date.getDate() + offset);
  return `${MONTH_NAMES[date.getMonth()]} ${date.getDate()}`;
};

const buildAttributes = (
  id: string,
  spaceId: string,
  category: SpaceWithAttributes['category'],
  primaryPurpose: NonNullable<SpaceWithAttributes['primary_purpose']>,
  attributeScores: AttributeScores,
  totalRatings: number
) => ({
  id,
  space_id: spaceId,
  category,
  primary_purpose: primaryPurpose,
  attribute_scores: attributeScores,
  overall_score: calculateOverallScore(attributeScores),
  total_ratings: totalRatings,
  created_at: now,
  updated_at: now,
});

export const demoCurrentUserId = 'user-sarah';

export const demoProfiles: Profile[] = [
  {
    id: 'profile-sarah',
    user_id: demoCurrentUserId,
    username: 'sarah_explores',
    vibe_title: 'Work Junkie',
    full_name: 'Sarah Chen',
    bio: 'Digital nomad, coffee enthusiast, and third-space hunter.',
    location: 'Arlington, VA',
    avatar_url: undefined,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'profile-mike',
    user_id: 'user-mike',
    username: 'mikeplays',
    vibe_title: 'Court Rat',
    full_name: 'Mike Rodriguez',
    bio: 'Pickup basketball and late-night food spots.',
    location: 'Arlington, VA',
    avatar_url: undefined,
    is_following: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'profile-emma',
    user_id: 'user-emma',
    username: 'emma_reads',
    vibe_title: 'Urban Explorer',
    full_name: 'Emma Thompson',
    bio: 'Quiet corners, libraries, and public spaces.',
    location: 'Washington, DC',
    avatar_url: undefined,
    is_following: false,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'profile-nina',
    user_id: 'user-nina',
    username: 'nina_nights',
    vibe_title: 'Late Night Viber',
    full_name: 'Nina Patel',
    bio: 'Cozy bars and sunset overlooks.',
    location: 'Alexandria, VA',
    avatar_url: undefined,
    is_following: true,
    created_at: now,
    updated_at: now,
  },
];

export const demoSpaces: SpaceWithAttributes[] = [
  {
    id: '00000000-0000-0000-0000-000000000101',
    name: 'Northside Social',
    category: 'Cafe & Coworking',
    primary_purpose: 'Remote Work',
    address: '3211 Wilson Blvd, Arlington, VA 22201',
    latitude: 38.8816,
    longitude: -77.1081,
    description: 'Specialty coffee and a reliable upstairs work zone in Clarendon.',
    website: 'https://northsidesocialarlington.com',
    phone: '+17034657777',
    hours: 'Mon-Fri 7am-7pm, Sat-Sun 8am-7pm',
    created_at: now,
    updated_at: now,
    favorites_count: 42,
    current_user_favorited: true,
    attributes: buildAttributes(
      'attr-northside-social',
      '00000000-0000-0000-0000-000000000101',
      'Cafe & Coworking',
      'Remote Work',
      { wifi_quality: 5, outlet_density: 4, quietness: 4, chair_comfort: 4 },
      28
    ),
  },
  {
    id: '00000000-0000-0000-0000-000000000102',
    name: 'Crystal City Water Park',
    category: 'Park & Nature',
    primary_purpose: 'Picnic',
    address: '1750 Crystal Dr, Arlington, VA 22202',
    latitude: 38.8574,
    longitude: -77.0502,
    description: 'Outdoor seating, water features, and a strong lunch-break reset.',
    website: 'https://www.crystalcitywaterpark.com',
    hours: 'Daily 7am-10pm',
    created_at: now,
    updated_at: now,
    favorites_count: 25,
    current_user_favorited: false,
    attributes: buildAttributes(
      'attr-crystal-water-park',
      '00000000-0000-0000-0000-000000000102',
      'Park & Nature',
      'Picnic',
      { scenery_views: 5, seating_benches: 4, shade_cover: 3, cleanliness: 4 },
      15
    ),
  },
  {
    id: '00000000-0000-0000-0000-000000000103',
    name: 'Arlington Central Library Atrium',
    category: 'Public Architecture (Atriums, Hotel Lobbies)',
    primary_purpose: 'Lobby Work',
    address: '1015 N Quincy St, Arlington, VA 22201',
    latitude: 38.8859,
    longitude: -77.1364,
    description: 'Bright public atrium with calm seating and dependable focus energy.',
    website: 'https://library.arlingtonva.us',
    hours: 'Mon-Thu 10am-9pm, Fri-Sat 10am-5pm, Sun 1pm-5pm',
    created_at: now,
    updated_at: now,
    favorites_count: 31,
    current_user_favorited: false,
    attributes: buildAttributes(
      'attr-central-library-atrium',
      '00000000-0000-0000-0000-000000000103',
      'Public Architecture (Atriums, Hotel Lobbies)',
      'Lobby Work',
      { people_watching: 4, design_aesthetic: 5, public_restrooms: 3, comfort: 4 },
      22
    ),
  },
  {
    id: '00000000-0000-0000-0000-000000000104',
    name: 'The Board Room',
    category: 'Interactive Fun (Arcades, Board Games)',
    primary_purpose: 'Board Game Night',
    address: '925 N Garfield St, Arlington, VA 22201',
    latitude: 38.8839,
    longitude: -77.0948,
    description: 'Board-game bar with a deep game library and easy group tables. Karaoke Friday nights from 9pm.',
    website: 'https://theboardroomva.com',
    phone: '+17032434075',
    hours: 'Tue-Thu 4pm-11pm, Fri-Sat 12pm-1am, Sun 12pm-10pm',
    created_at: now,
    updated_at: now,
    favorites_count: 36,
    current_user_favorited: true,
    attributes: buildAttributes(
      'attr-board-room',
      '00000000-0000-0000-0000-000000000104',
      'Interactive Fun (Arcades, Board Games)',
      'Board Game Night',
      { gear_game_quality: 5, group_friendliness: 5, cost_value: 4, atmosphere: 4 },
      35
    ),
  },
  {
    id: '00000000-0000-0000-0000-000000000105',
    name: 'Gravelly Point',
    category: 'Smoke & Sunset Spots',
    primary_purpose: 'Sunset Watch',
    address: 'George Washington Memorial Pkwy, Arlington, VA 22202',
    latitude: 38.8646,
    longitude: -77.0397,
    description: 'Wide-open skyline and plane-watching spot near the river.',
    created_at: now,
    updated_at: now,
    favorites_count: 51,
    current_user_favorited: false,
    attributes: buildAttributes(
      'attr-gravelly-point',
      '00000000-0000-0000-0000-000000000105',
      'Smoke & Sunset Spots',
      'Sunset Watch',
      { privacy_seclusion: 3, view_quality: 5, wind_shelter: 2, chill_factor: 5 },
      44
    ),
  },
];

const buildSecretSpace = (
  space: Omit<SpaceWithAttributes, 'created_at' | 'updated_at' | 'is_secret' | 'attributes'> & {
    primary_purpose: NonNullable<SpaceWithAttributes['primary_purpose']>;
  },
  attributeScores: AttributeScores,
  totalRatings: number
): SpaceWithAttributes => ({
  ...space,
  is_secret: true,
  created_at: now,
  updated_at: now,
  attributes: buildAttributes(`attr-${space.id}`, space.id, space.category, space.primary_purpose, attributeScores, totalRatings),
});

export const demoSecretSpaces: SpaceWithAttributes[] = [
  buildSecretSpace(
    {
      id: 'secret-nina-rooftop',
      name: 'Top Deck at Rosslyn Garage',
      category: 'Smoke & Sunset Spots',
      primary_purpose: 'Sunset Watch',
      address: '1800 N Lynn St, Arlington, VA 22209',
      latitude: 38.8962,
      longitude: -77.0712,
      description: 'Top floor of a quiet garage with a full skyline view. Empty after 7pm.',
      created_by: 'user-nina',
      area_hint: 'Rosslyn - skyline views, bring a jacket',
    },
    { privacy_seclusion: 5, view_quality: 5, wind_shelter: 2, chill_factor: 5 },
    3
  ),
  buildSecretSpace(
    {
      id: 'secret-mike-halfcourt',
      name: 'Church Lot Half-Court',
      category: 'Sports Area',
      primary_purpose: 'Night Session',
      address: 'N Pershing Dr, Arlington, VA 22201',
      latitude: 38.8781,
      longitude: -77.0925,
      description: 'Solid half-court behind the parish hall. Lights stay on until 11.',
      created_by: 'user-mike',
      area_hint: 'Lyon Park - lights stay on late',
    },
    { court_field_quality: 4, night_lighting: 5, crowdedness: 5, amenities: 2 },
    2
  ),
  buildSecretSpace(
    {
      id: 'secret-emma-mezzanine',
      name: 'Hotel Mezzanine Reading Nook',
      category: 'Public Architecture (Atriums, Hotel Lobbies)',
      primary_purpose: 'Lobby Work',
      address: '1250 S Hayes St, Arlington, VA 22202',
      latitude: 38.8627,
      longitude: -77.0596,
      description: 'Upstairs mezzanine with armchairs and outlets. Nobody goes up there.',
      created_by: 'user-emma',
      area_hint: 'Pentagon City - nobody goes upstairs',
    },
    { people_watching: 3, design_aesthetic: 4, public_restrooms: 5, comfort: 5 },
    2
  ),
  buildSecretSpace(
    {
      id: 'secret-sarah-bench',
      name: 'Fort C.F. Smith Hilltop Bench',
      category: 'Park & Nature',
      primary_purpose: 'Reading',
      address: '2411 N 24th St, Arlington, VA 22207',
      latitude: 38.9016,
      longitude: -77.1036,
      description: 'A single bench at the top of the meadow. Quietest spot in the county.',
      created_by: demoCurrentUserId,
      area_hint: 'North Arlington - the quietest bench around',
    },
    { scenery_views: 5, seating_benches: 3, shade_cover: 4, cleanliness: 5 },
    1
  ),
];

export const demoSecretAccess = [`${demoCurrentUserId}:secret-emma-mezzanine`];

export const demoSecretRequests: SecretSpotRequest[] = [
  {
    id: 'secret-request-1',
    space_id: 'secret-sarah-bench',
    requester_id: 'user-emma',
    owner_id: demoCurrentUserId,
    kind: 'request',
    message: 'Heard you found the quietest bench in Arlington. I promise to keep it quiet!',
    status: 'pending',
    created_at: '2026-05-26T09:00:00Z',
  },
  {
    id: 'secret-request-2',
    space_id: 'secret-sarah-bench',
    requester_id: 'user-mike',
    owner_id: demoCurrentUserId,
    kind: 'trade',
    offered_space_id: 'secret-mike-halfcourt',
    status: 'pending',
    created_at: '2026-05-26T12:00:00Z',
  },
];

export const demoFeed: FeedActivity[] = [
  {
    id: 'rating-1',
    user_id: demoCurrentUserId,
    space_id: demoSpaces[0].id,
    category: 'Cafe & Coworking',
    primary_purpose: 'Remote Work',
    attribute_scores: demoSpaces[0].attributes!.attribute_scores,
    overall_score: demoSpaces[0].attributes!.overall_score,
    review_text: 'Perfect spot for remote work. Fast Wi-Fi, good coffee, and the upstairs area stays focused.',
    likes_count: 12,
    comments_count: 2,
    current_user_liked: false,
    created_at: '2026-05-25T10:30:00Z',
    space: demoSpaces[0],
    profile: demoProfiles[0],
  },
  {
    id: 'rating-2',
    user_id: 'user-mike',
    space_id: demoSpaces[3].id,
    category: 'Interactive Fun (Arcades, Board Games)',
    primary_purpose: 'Board Game Night',
    attribute_scores: demoSpaces[3].attributes!.attribute_scores,
    overall_score: demoSpaces[3].attributes!.overall_score,
    review_text: 'Great group energy and the staff helps pick games without making it awkward.',
    likes_count: 18,
    comments_count: 3,
    current_user_liked: true,
    created_at: '2026-05-24T20:15:00Z',
    space: demoSpaces[3],
    profile: demoProfiles[1],
    is_following: true,
  },
  {
    id: 'rating-3',
    user_id: 'user-emma',
    space_id: demoSpaces[2].id,
    category: 'Public Architecture (Atriums, Hotel Lobbies)',
    primary_purpose: 'Lobby Work',
    attribute_scores: demoSpaces[2].attributes!.attribute_scores,
    overall_score: demoSpaces[2].attributes!.overall_score,
    review_text: 'Excellent low-cost study environment. Limited hours, but very worth planning around.',
    likes_count: 15,
    comments_count: 1,
    current_user_liked: false,
    created_at: '2026-05-23T16:45:00Z',
    space: demoSpaces[2],
    profile: demoProfiles[2],
    is_following: false,
  },
  {
    id: 'rating-4',
    user_id: 'user-nina',
    space_id: demoSpaces[4].id,
    category: 'Smoke & Sunset Spots',
    primary_purpose: 'Late-Night Chill',
    attribute_scores: demoSpaces[4].attributes!.attribute_scores,
    overall_score: demoSpaces[4].attributes!.overall_score,
    review_text: 'Planes overhead, city lights across the river. Windy, but nothing beats it at 10pm.',
    likes_count: 22,
    comments_count: 0,
    current_user_liked: false,
    created_at: '2026-05-25T02:10:00Z',
    space: demoSpaces[4],
    profile: demoProfiles[3],
    is_following: true,
  },
  {
    id: 'rating-5',
    user_id: 'user-nina',
    space_id: demoSecretSpaces[0].id,
    category: 'Smoke & Sunset Spots',
    primary_purpose: 'Sunset Watch',
    attribute_scores: demoSecretSpaces[0].attributes!.attribute_scores,
    overall_score: demoSecretSpaces[0].attributes!.overall_score,
    review_text: 'Not telling anyone where this is. Best sunset in Arlington.',
    likes_count: 9,
    comments_count: 0,
    current_user_liked: false,
    created_at: '2026-05-24T23:40:00Z',
    space: demoSecretSpaces[0],
    profile: demoProfiles[3],
    is_following: true,
  },
  {
    id: 'rating-6',
    user_id: 'user-emma',
    space_id: demoSecretSpaces[2].id,
    category: 'Public Architecture (Atriums, Hotel Lobbies)',
    primary_purpose: 'Lobby Work',
    attribute_scores: demoSecretSpaces[2].attributes!.attribute_scores,
    overall_score: demoSecretSpaces[2].attributes!.overall_score,
    review_text: 'Armchairs, outlets, and total silence. Thanks for keeping this one between us.',
    likes_count: 4,
    comments_count: 0,
    current_user_liked: false,
    created_at: '2026-05-22T15:00:00Z',
    space: demoSecretSpaces[2],
    profile: demoProfiles[2],
    is_following: false,
  },
  {
    id: 'rating-7',
    user_id: 'user-mike',
    space_id: demoSpaces[3].id,
    category: 'Interactive Fun (Arcades, Board Games)',
    primary_purpose: 'Group Games',
    attribute_scores: demoSpaces[3].attributes!.attribute_scores,
    overall_score: demoSpaces[3].attributes!.overall_score,
    review_text: `Trivia every Tuesday at 8pm and the hosts are hilarious. Teams of up to six, show up early. Comedy night on ${dayFromNow(35)} at 9pm too.`,
    likes_count: 14,
    comments_count: 0,
    current_user_liked: false,
    created_at: daysAgo(3),
    space: demoSpaces[3],
    profile: demoProfiles[1],
    is_following: true,
  },
  {
    id: 'rating-8',
    user_id: 'user-nina',
    space_id: demoSpaces[0].id,
    category: 'Cafe & Coworking',
    primary_purpose: 'Casual Hangout',
    attribute_scores: demoSpaces[0].attributes!.attribute_scores,
    overall_score: demoSpaces[0].attributes!.overall_score,
    review_text: `Open mic night on ${dayFromNow(9)} at 7:30pm, sign-ups at instagram.com/northsidesocial. Bring a friend!`,
    likes_count: 7,
    comments_count: 0,
    current_user_liked: false,
    created_at: daysAgo(1),
    space: demoSpaces[0],
    profile: demoProfiles[3],
    is_following: true,
  },
  {
    id: 'rating-9',
    user_id: 'user-emma',
    space_id: demoSpaces[2].id,
    category: 'Public Architecture (Atriums, Hotel Lobbies)',
    primary_purpose: 'Rest Break',
    attribute_scores: demoSpaces[2].attributes!.attribute_scores,
    overall_score: demoSpaces[2].attributes!.overall_score,
    review_text: 'They host a book club in the atrium. Next one is this Saturday at 2pm, totally free.',
    likes_count: 5,
    comments_count: 0,
    current_user_liked: false,
    created_at: daysAgo(2),
    space: demoSpaces[2],
    profile: demoProfiles[2],
    is_following: false,
  },
  {
    id: 'rating-10',
    user_id: demoCurrentUserId,
    space_id: demoSpaces[1].id,
    category: 'Park & Nature',
    primary_purpose: 'Walking',
    attribute_scores: demoSpaces[1].attributes!.attribute_scores,
    overall_score: demoSpaces[1].attributes!.overall_score,
    review_text: `Farmers market every Saturday morning from 9am. Also a jazz night on ${dayFromNow(16)} at 7pm, see crystalcity.org/events for the lineup.`,
    likes_count: 11,
    comments_count: 0,
    current_user_liked: false,
    created_at: daysAgo(4),
    space: demoSpaces[1],
    profile: demoProfiles[0],
  },
  {
    id: 'rating-11',
    user_id: 'user-mike',
    space_id: demoSpaces[4].id,
    category: 'Smoke & Sunset Spots',
    primary_purpose: 'Sunset Watch',
    attribute_scores: demoSpaces[4].attributes!.attribute_scores,
    overall_score: demoSpaces[4].attributes!.overall_score,
    review_text: "Run club meets here every Thursday at 6:30pm for a sunset loop. Everyone's welcome.",
    likes_count: 9,
    comments_count: 0,
    current_user_liked: false,
    created_at: daysAgo(5),
    space: demoSpaces[4],
    profile: demoProfiles[1],
    is_following: true,
  },
];

export const demoComments: ReviewComment[] = [
  {
    id: 'comment-1',
    rating_id: 'rating-1',
    user_id: 'user-mike',
    body: 'The upstairs tables are clutch before noon.',
    created_at: '2026-05-25T12:00:00Z',
    profile: demoProfiles[1],
  },
  {
    id: 'comment-2',
    rating_id: 'rating-1',
    user_id: 'user-nina',
    body: 'Adding this to my work rotation.',
    created_at: '2026-05-25T13:00:00Z',
    profile: demoProfiles[3],
  },
];

const unsplashUrl = (photoId: string) => `https://images.unsplash.com/photo-${photoId}?w=1600&q=75&fm=jpg&fit=max`;

const buildDemoPhoto = (
  id: string,
  owner: { ratingId: string } | { commentId: string },
  photoId: string,
  height: number
): ReviewPhoto => {
  const ratingId = 'ratingId' in owner
    ? owner.ratingId
    : demoComments.find((comment) => comment.id === owner.commentId)!.rating_id;
  const rating = demoFeed.find((activity) => activity.id === ratingId)!;
  const comment = 'commentId' in owner ? demoComments.find((item) => item.id === owner.commentId)! : undefined;

  return {
    id,
    user_id: comment?.user_id ?? rating.user_id,
    space_id: rating.space_id,
    rating_id: comment ? undefined : rating.id,
    comment_id: comment?.id,
    url: unsplashUrl(photoId),
    width: 1600,
    height,
    created_at: comment?.created_at ?? rating.created_at,
    profile: comment?.profile ?? rating.profile,
  };
};

export const demoPhotos: ReviewPhoto[] = [
  buildDemoPhoto('photo-1', { ratingId: 'rating-1' }, '1554118811-1e0d58224f24', 1096),
  buildDemoPhoto('photo-2', { ratingId: 'rating-1' }, '1495474472287-4d71bcdd2085', 1068),
  buildDemoPhoto('photo-3', { commentId: 'comment-1' }, '1521017432531-fbd92d768814', 1068),
  buildDemoPhoto('photo-4', { ratingId: 'rating-8' }, '1501339847302-ac426a4a7cbb', 1056),
  buildDemoPhoto('photo-5', { ratingId: 'rating-2' }, '1610890716171-6b1bb98ffd09', 900),
  buildDemoPhoto('photo-6', { ratingId: 'rating-2' }, '1606167668584-78701c57f13d', 1068),
  buildDemoPhoto('photo-7', { ratingId: 'rating-3' }, '1568667256549-094345857637', 2240),
  buildDemoPhoto('photo-8', { ratingId: 'rating-3' }, '1521587760476-6c12a4b040da', 1068),
  buildDemoPhoto('photo-9', { ratingId: 'rating-9' }, '1507842217343-583bb7270b66', 940),
  buildDemoPhoto('photo-10', { ratingId: 'rating-4' }, '1514565131-fce0801e5785', 972),
  buildDemoPhoto('photo-11', { ratingId: 'rating-4' }, '1436491865332-7a61a109cc05', 1064),
  buildDemoPhoto('photo-12', { ratingId: 'rating-11' }, '1495616811223-4d98c6e9c869', 900),
  buildDemoPhoto('photo-13', { ratingId: 'rating-10' }, '1490750967868-88aa4486c946', 1068),
  buildDemoPhoto('photo-14', { ratingId: 'rating-10' }, '1529156069898-49953e39b3ac', 900),
  buildDemoPhoto('photo-15', { ratingId: 'rating-5' }, '1477959858617-67f85cf4f1df', 984),
];

export const demoRankings: (UserRanking & { space: SpaceWithAttributes })[] = [
  {
    id: 'ranking-1',
    user_id: demoCurrentUserId,
    space_id: demoSpaces[0].id,
    personal_rank: 1,
    notes: 'My go-to morning work spot.',
    is_favorite: true,
    last_visited: '2026-05-25T09:00:00Z',
    created_at: now,
    updated_at: now,
    space: demoSpaces[0],
  },
  {
    id: 'ranking-2',
    user_id: demoCurrentUserId,
    space_id: demoSpaces[3].id,
    personal_rank: 2,
    notes: 'Best easy group hangout.',
    is_favorite: true,
    last_visited: '2026-05-24T19:30:00Z',
    created_at: now,
    updated_at: now,
    space: demoSpaces[3],
  },
  {
    id: 'ranking-3',
    user_id: demoCurrentUserId,
    space_id: demoSpaces[2].id,
    personal_rank: 3,
    notes: 'Great for quiet reset sessions.',
    is_favorite: false,
    last_visited: '2026-05-22T11:00:00Z',
    created_at: now,
    updated_at: now,
    space: demoSpaces[2],
  },
];

export const demoProfile: ProfileWithStats = {
  ...demoProfiles[0],
  stats: {
    spaces_rated: 28,
    reviews_written: 15,
    helpful_votes: 142,
    rank_in_area: 3,
    followers: 384,
    following: 126,
  },
};
