import {
  calculateOverallScore,
  type AttributeScores,
  type FeedActivity,
  type Profile,
  type ProfileWithStats,
  type ReviewComment,
  type SpaceWithAttributes,
  type UserRanking,
} from '@/types/space';

const now = new Date().toISOString();

const buildAttributes = (
  id: string,
  spaceId: string,
  category: SpaceWithAttributes['category'],
  primaryPurpose: NonNullable<SpaceWithAttributes['primary_purpose']>,
  attributeScores: AttributeScores,
  totalRatings: number
) => ({
  id,
  space_id: spaceId,
  category,
  primary_purpose: primaryPurpose,
  attribute_scores: attributeScores,
  overall_score: calculateOverallScore(attributeScores),
  total_ratings: totalRatings,
  created_at: now,
  updated_at: now,
});

export const demoCurrentUserId = 'user-sarah';

export const demoProfiles: Profile[] = [
  {
    id: 'profile-sarah',
    user_id: demoCurrentUserId,
    username: 'sarah_explores',
    full_name: 'Sarah Chen',
    bio: 'Digital nomad, coffee enthusiast, and third-space hunter.',
    location: 'Arlington, VA',
    avatar_url: undefined,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'profile-mike',
    user_id: 'user-mike',
    username: 'mikeplays',
    full_name: 'Mike Rodriguez',
    bio: 'Pickup basketball and late-night food spots.',
    location: 'Arlington, VA',
    avatar_url: undefined,
    is_following: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'profile-emma',
    user_id: 'user-emma',
    username: 'emma_reads',
    full_name: 'Emma Thompson',
    bio: 'Quiet corners, libraries, and public spaces.',
    location: 'Washington, DC',
    avatar_url: undefined,
    is_following: false,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'profile-nina',
    user_id: 'user-nina',
    username: 'nina_nights',
    full_name: 'Nina Patel',
    bio: 'Cozy bars and sunset overlooks.',
    location: 'Alexandria, VA',
    avatar_url: undefined,
    is_following: true,
    created_at: now,
    updated_at: now,
  },
];

export const demoSpaces: SpaceWithAttributes[] = [
  {
    id: '00000000-0000-0000-0000-000000000101',
    name: 'Northside Social',
    category: 'Cafe & Coworking',
    primary_purpose: 'Remote Work',
    address: '3211 Wilson Blvd, Arlington, VA 22201',
    latitude: 38.8816,
    longitude: -77.1081,
    description: 'Specialty coffee and a reliable upstairs work zone in Clarendon.',
    website: 'https://northsidesocialarlington.com',
    phone: '+17034657777',
    hours: 'Mon-Fri 7am-7pm, Sat-Sun 8am-7pm',
    created_at: now,
    updated_at: now,
    favorites_count: 42,
    current_user_favorited: true,
    attributes: buildAttributes(
      'attr-northside-social',
      '00000000-0000-0000-0000-000000000101',
      'Cafe & Coworking',
      'Remote Work',
      { wifi_quality: 5, outlet_density: 4, quietness: 4, chair_comfort: 4 },
      28
    ),
  },
  {
    id: '00000000-0000-0000-0000-000000000102',
    name: 'Crystal City Water Park',
    category: 'Park & Nature',
    primary_purpose: 'Picnic',
    address: '1750 Crystal Dr, Arlington, VA 22202',
    latitude: 38.8574,
    longitude: -77.0502,
    description: 'Outdoor seating, water features, and a strong lunch-break reset.',
    website: 'https://www.crystalcitywaterpark.com',
    hours: 'Daily 7am-10pm',
    created_at: now,
    updated_at: now,
    favorites_count: 25,
    current_user_favorited: false,
    attributes: buildAttributes(
      'attr-crystal-water-park',
      '00000000-0000-0000-0000-000000000102',
      'Park & Nature',
      'Picnic',
      { scenery_views: 5, seating_benches: 4, shade_cover: 3, cleanliness: 4 },
      15
    ),
  },
  {
    id: '00000000-0000-0000-0000-000000000103',
    name: 'Arlington Central Library Atrium',
    category: 'Public Architecture (Atriums, Hotel Lobbies)',
    primary_purpose: 'Lobby Work',
    address: '1015 N Quincy St, Arlington, VA 22201',
    latitude: 38.8859,
    longitude: -77.1364,
    description: 'Bright public atrium with calm seating and dependable focus energy.',
    website: 'https://library.arlingtonva.us',
    hours: 'Mon-Thu 10am-9pm, Fri-Sat 10am-5pm, Sun 1pm-5pm',
    created_at: now,
    updated_at: now,
    favorites_count: 31,
    current_user_favorited: false,
    attributes: buildAttributes(
      'attr-central-library-atrium',
      '00000000-0000-0000-0000-000000000103',
      'Public Architecture (Atriums, Hotel Lobbies)',
      'Lobby Work',
      { people_watching: 4, design_aesthetic: 5, public_restrooms: 3, comfort: 4 },
      22
    ),
  },
  {
    id: '00000000-0000-0000-0000-000000000104',
    name: 'The Board Room',
    category: 'Interactive Fun (Arcades, Board Games)',
    primary_purpose: 'Board Game Night',
    address: '925 N Garfield St, Arlington, VA 22201',
    latitude: 38.8839,
    longitude: -77.0948,
    description: 'Board-game bar with a deep game library and easy group tables.',
    website: 'https://theboardroomva.com',
    phone: '+17032434075',
    hours: 'Tue-Thu 4pm-11pm, Fri-Sat 12pm-1am, Sun 12pm-10pm',
    created_at: now,
    updated_at: now,
    favorites_count: 36,
    current_user_favorited: true,
    attributes: buildAttributes(
      'attr-board-room',
      '00000000-0000-0000-0000-000000000104',
      'Interactive Fun (Arcades, Board Games)',
      'Board Game Night',
      { gear_game_quality: 5, group_friendliness: 5, cost_value: 4, atmosphere: 4 },
      35
    ),
  },
  {
    id: '00000000-0000-0000-0000-000000000105',
    name: 'Gravelly Point',
    category: 'Smoke & Sunset Spots',
    primary_purpose: 'Sunset Watch',
    address: 'George Washington Memorial Pkwy, Arlington, VA 22202',
    latitude: 38.8646,
    longitude: -77.0397,
    description: 'Wide-open skyline and plane-watching spot near the river.',
    created_at: now,
    updated_at: now,
    favorites_count: 51,
    current_user_favorited: false,
    attributes: buildAttributes(
      'attr-gravelly-point',
      '00000000-0000-0000-0000-000000000105',
      'Smoke & Sunset Spots',
      'Sunset Watch',
      { privacy_seclusion: 3, view_quality: 5, wind_shelter: 2, chill_factor: 5 },
      44
    ),
  },
];

export const demoFeed: FeedActivity[] = [
  {
    id: 'rating-1',
    user_id: demoCurrentUserId,
    space_id: demoSpaces[0].id,
    category: 'Cafe & Coworking',
    primary_purpose: 'Remote Work',
    attribute_scores: demoSpaces[0].attributes!.attribute_scores,
    overall_score: demoSpaces[0].attributes!.overall_score,
    review_text: 'Perfect spot for remote work. Fast Wi-Fi, good coffee, and the upstairs area stays focused.',
    likes_count: 12,
    comments_count: 2,
    current_user_liked: false,
    created_at: '2026-05-25T10:30:00Z',
    space: demoSpaces[0],
    profile: demoProfiles[0],
  },
  {
    id: 'rating-2',
    user_id: 'user-mike',
    space_id: demoSpaces[3].id,
    category: 'Interactive Fun (Arcades, Board Games)',
    primary_purpose: 'Board Game Night',
    attribute_scores: demoSpaces[3].attributes!.attribute_scores,
    overall_score: demoSpaces[3].attributes!.overall_score,
    review_text: 'Great group energy and the staff helps pick games without making it awkward.',
    likes_count: 18,
    comments_count: 3,
    current_user_liked: true,
    created_at: '2026-05-24T20:15:00Z',
    space: demoSpaces[3],
    profile: demoProfiles[1],
    is_following: true,
  },
  {
    id: 'rating-3',
    user_id: 'user-emma',
    space_id: demoSpaces[2].id,
    category: 'Public Architecture (Atriums, Hotel Lobbies)',
    primary_purpose: 'Lobby Work',
    attribute_scores: demoSpaces[2].attributes!.attribute_scores,
    overall_score: demoSpaces[2].attributes!.overall_score,
    review_text: 'Excellent low-cost study environment. Limited hours, but very worth planning around.',
    likes_count: 15,
    comments_count: 1,
    current_user_liked: false,
    created_at: '2026-05-23T16:45:00Z',
    space: demoSpaces[2],
    profile: demoProfiles[2],
    is_following: false,
  },
];

export const demoComments: ReviewComment[] = [
  {
    id: 'comment-1',
    rating_id: 'rating-1',
    user_id: 'user-mike',
    body: 'The upstairs tables are clutch before noon.',
    created_at: '2026-05-25T12:00:00Z',
    profile: demoProfiles[1],
  },
  {
    id: 'comment-2',
    rating_id: 'rating-1',
    user_id: 'user-nina',
    body: 'Adding this to my work rotation.',
    created_at: '2026-05-25T13:00:00Z',
    profile: demoProfiles[3],
  },
];

export const demoRankings: (UserRanking & { space: SpaceWithAttributes })[] = [
  {
    id: 'ranking-1',
    user_id: demoCurrentUserId,
    space_id: demoSpaces[0].id,
    personal_rank: 1,
    notes: 'My go-to morning work spot.',
    is_favorite: true,
    last_visited: '2026-05-25T09:00:00Z',
    created_at: now,
    updated_at: now,
    space: demoSpaces[0],
  },
  {
    id: 'ranking-2',
    user_id: demoCurrentUserId,
    space_id: demoSpaces[3].id,
    personal_rank: 2,
    notes: 'Best easy group hangout.',
    is_favorite: true,
    last_visited: '2026-05-24T19:30:00Z',
    created_at: now,
    updated_at: now,
    space: demoSpaces[3],
  },
  {
    id: 'ranking-3',
    user_id: demoCurrentUserId,
    space_id: demoSpaces[2].id,
    personal_rank: 3,
    notes: 'Great for quiet reset sessions.',
    is_favorite: false,
    last_visited: '2026-05-22T11:00:00Z',
    created_at: now,
    updated_at: now,
    space: demoSpaces[2],
  },
];

export const demoProfile: ProfileWithStats = {
  ...demoProfiles[0],
  stats: {
    spaces_rated: 28,
    reviews_written: 15,
    helpful_votes: 142,
    rank_in_area: 3,
    followers: 384,
    following: 126,
  },
};
